### ISSUE TITLE
Slovakia numbers - short numbers and proper area code detection

### ISSUE THREAD

**Issue by lfrailey** [googlei18n/libphonenumber#1147]
Country/region affected (e.g., "US"): Slovakia
Example number(s) affected ("+1 555 555-1234"): +421216877
The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): see below
The type of the number(s) ("fixed-line", "mobile", "short code", etc.): see below
Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article):

There are certain valid Slovak numbers that aren't recognized correctly. There are two main issues:
1) There are short numbers that don't have an area code (1911 and 18333 in the table below). These numbers can be dialed from everywhere in the country and don't have an area code at all, so there's no area code we can put in to make them work. The Google Library doesn't recognize these.
2) There's also another issue with how the lib is interpreting certain numbers. When you validate +421216877, then 42 is interpreted as the area code (which maps to a city called "Považská Bystrica") - however, this is not the intention, the +421 is the country code and the '2' is the area code (for Bratislava). 

![slovakia number table](https://cloud.githubusercontent.com/assets/11136017/15845770/3f912660-2c44-11e6-9f9e-94b3c175597a.png)

**Valid SK phone numbers (regex that we use):**
 
/*international*/
(ALLTRIM(ncountrycd) == '421');
  AND ;
(;
/*short nomad phone numbers */
(EMPTY(ncitycd) AND RegExp(ALLTRIM(CHRTRAN(ncvalue, ' ', '')), '019[0-9]{2}'));
 
/*long landline phone numbers for Bratislava region*/
  OR (RegExp(ALLTRIM(ncitycd),'02') AND RegExp(ALLTRIM(CHRTRAN(ncvalue, ' ', '')), '[2-9][0-9]{7}'));
 
/*long landline phone numbers for other regions of Slovakia*/
  OR (RegExp(ALLTRIM(ncitycd),'0[3-5][1-8]') AND RegExp(ALLTRIM(CHRTRAN(ncvalue, ' ', '')), '[2-9][0-9]{6}'));
 
/*long nomad other phone numbers*/
  OR (EMPTY(ncitycd) AND RegExp(ALLTRIM(CHRTRAN(ncvalue, ' ', '')), '06(0[1-2][0-9]{6}|5[0-4][0-9]{6}|9[0-6][0-9]{6})'));
  OR (EMPTY(ncitycd) AND RegExp(ALLTRIM(CHRTRAN(ncvalue, ' ', '')), '08((00|0[6-9]|[5-9][0-9])[0-9]{6}|190000[0-9]{2})'));
 
/*long nomad mobile phone numbers */
  OR (EMPTY(ncitycd) AND RegExp(ALLTRIM(CHRTRAN(ncvalue, ' ', '')), '09(00|0[1-9]|[1,4-5][0-9]|[6-8][0-9])[0-9]{6}'));
 
/*short nomad phone numbers*/
  OR (EMPTY(ncitycd) AND RegExp(ALLTRIM(CHRTRAN(ncvalue, ' ', '')), '1(0[0-9]{2}|1[0-9]{1,4}|[2-4,8][0-9]{3}|5[0,5,8,9])'));
 
/*short phone numbers*/
  OR (RegExp(ALLTRIM(ncitycd),'0(2|[3-5][1-8])') AND RegExp(ALLTRIM(CHRTRAN(ncvalue, ' ', '')), '1[6-7][0-9]{3}'));
)

**Comment by padmaksha** [comment]
@lfrailey 

Thank you for taking the time to improve libphonenumber!

With respect to supporting the short numbers 1911 and 18333, we can't find official evidence that the ranges are valid. Please share any official evidence you may have. See our
[guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

With regards to your other query on the number “+421216877” being parsed and returning an unexpected geocode,  this is working as intended. It would not happen if you didn't have  the “+” symbol at the beginning of the number. 
When the number “+421216877” is parsed with the “+” symbol it correctly identifies the country code as 421(slovakia). Please see [demo](http://libphonenumber.appspot.com/phonenumberparser?number=%2B421216877&country=SK). 
When the “+” symbol is omitted (421216877 is provided as input with country code SK) , it is parsed as a national number and interprets 421 as the area code. This is the same number as when providing  +421421216877 as input. So the parsing of the number is working as intended . [demo](http://libphonenumber.appspot.com/phonenumberparser?number=421216877&country=SK).
How are you using the library? Are the input numbers (like +421216877) provided by users and  do you strip the leading “+” symbol before validating them (shouldn't do this to user-provided input by the way, then you'd get unexpected results)?
You can find how the parse method works [here](https://github.com/googlei18n/libphonenumber/blob/master/java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java#L2772).

**Comment by lfrailey** [comment]
This is a government record explaining phone formats in Slovakia. §7 talks about these shortened numbers:
http://www.teleoff.gov.sk/data/files/25211.pdf

We'll look into the parsing and get back to you if there are still issues. 

Thanks!

**Comment by padmaksha** [comment]
Thanks for providing all the details we need! We've accepted this issue and
will fix this in an upcoming release.

Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

**Comment by padmaksha** [comment]
@lfrailey

We will be adding 18XXX range short numbers. 
With respect to the short numbers 19XX , these numbers are used for accessing data services from PSTN networks which we do not support at the moment.

Thanks

**Comment by padmaksha** [comment]
Fixed in release 7.4.4
http://repo1.maven.org/maven2/com/googlecode/libphonenumber/libphonenumber/7.4.4

**Comment by lfrailey** [comment]
Hi there, 

We're having trouble validating the change. For example, using the same number provided above (18 333) we're still receiving an invalid number: https://libphonenumber.appspot.com/phonenumberparser?number=%2B421+18+333&country=SK. 

We do see that the isValidShortNumber is TRUE, but isPossibleNumber is FALSE. What's the difference between these? There aren't valid formatting results either. 

If you could explain this a bit more, that would be very helpful. 

Thanks!
Liz

**Comment by lararennie** [comment]
To validate short numbers, you need to use ShortNumberInfo.
PhoneNumberUtil, and its method isPossibleNumber, will return false.

Formatting is tricky: we don't prioritise formatting short numbers because
there is no standard, and we also don't want the as-you-type-formatter to
perform worse for cases where national numbers that are incomplete clash
with short numbers, so usually we just do them as a block unless we have a
good reason to do something else. Here you'll see 18333 is formatted as a
block.

2016-07-06 21:49 GMT+02:00 lfrailey <notifications@github.com>:
