### ISSUE TITLE
NEW IR 21

### ISSUE THREAD

**Issue by GMSAG** [googlei18n/libphonenumber#1895]
Country: Uzbekistan
*   Example number(s) and/or range(s): 996 50X XXXXXX ).
*   Number type ("fixed-line", "mobile", "short code", etc.): mobile 
*   For short codes, cost and dialing restrictions: 
*   Where or whom did you get the number(s) from: Mobile Operator NurTelecom 
*   Authoritative evidence (e.g. national numbering plan, operator announcement): IR 21
*   Link from demo (http://libphonenumber.appspot.com) showing error:

**Comment by kkeshava** [comment]
@GMSAG,
Thank you for contributing to libphonenumber! For your next metadata issue, we invite you to file issues in Google's new [Issue Tracker](http://issuetracker.google.com/issues/new?component=192347), which we're currently testing. 

The country code 996 belongs to Kyrgyzstan and not Uzbekistan (998). Did you have a typo?

This is actually working as intended; +996 50X XXXXXX (eg. +996 500 123456) is already marked by our library as a valid *mobile* number with carrier *Nur Telecom*. Please see [demo](http://libphonenumber.appspot.com/phonenumberparser?number=%2B996+500+123456)

**Comment by kkeshava** [comment]
@GMSAG,
Would you please mention the exact prefix/s for which you are facing the issue? 
As mentioned in previous comment we are supporting all the ranges which starts with prefix 50 as Nur Telecom numbers in Kyrgyzstan. To check the latest behavior for yourself, see the demo (instructions in our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md)).

**Comment by GMSAG** [comment]
Dear kkeshave,

Please find an example below.

Users with the next number range are not able to register the Twitter account. 

996 ( 50 ) X XXXXXX.

We are doing day to day testing and can see that this problem still exists. 

Other services have already added this prefix and users can properly register a new account. Unfortunately, subscribers with 996 50 can not use Twitter. 

Thank you.

**Comment by GMSAG** [comment]
i have tried now by myself and it says - Please enter a valid phone number.

**Comment by kkeshava** [comment]
@GMSAG,
There are two ways of testing a number. 
1. You can either use E.164 format i.e '+996 (50) X XXXXXX', note that you need to add '+' before the country code http://libphonenumber.appspot.com/phonenumberparser?number=%2B996+%28+50+%29+X+XXXXXX 
In my second comment, I had tried with a sample number i.e +996 500 123456 http://libphonenumber.appspot.com/phonenumberparser?number=%2B996+500+123456
(or)
2. Feed the number with national prefix i.e '0 (50) X XXXXXX' and default country 'KG', see http://libphonenumber.appspot.com/phonenumberparser?number=0%28+50+%29+X+XXXXXX&country=KG

I see that you are using the first method. So request you do try the number again with '+'.

**Comment by GMSAG** [comment]
Dear Kkeshava,
Thank you for the examples of testing numbers. 
But we have tried to register a new account via Twitter App and it says that +966 500 123456: 966 500 123456 or any other option with 966 500 are not valid numbers. You can try on your own to register a Twitter account with this numbers. Twitter App and Web Page do not recognize this number range. Invalid numbers. Please provide me with your email and I will send a screenshot to you regarding this issue. 

Thank you for your time and cooperation.

**Comment by kkeshava** [comment]
@GMSAG,
Validation of number with prefix 50 was already fixed in 8.7.0 based on Nur Telecom’s IR 21 document.
Many products like Facebook, WhatsApp and other services use our open-source library. We are not aware of which version of our library they depend on hence we cannot determine whether the fix is already available there in their product. You may have to check with the respective product's Eng team.

**Comment by GMSAG** [comment]
Hi kkeshave, Twitter has forwarded us to this portal to put a request for a New IR 21.
New number range still doesn't work. Number is invalid. Whom we should contact regarding this issue.
Thank you for your time and cooperation.

**Comment by kkeshava** [comment]
@GMSAG,
As mentioned earlier, we have already fixed this from our end and that is the reason why it is working as intended in the [demo](http://libphonenumber.appspot.com/phonenumberparser?number=%2B996+%28+50+%29+X+XXXXXX). Twitter needs to upgrade to our latest release. 

I'll close this as it's not an issue with the library. Please consider joining the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd like to discuss this further.
