### ISSUE TITLE
Incorrect Time Zones Being Returned From PhoneNumberToTimeZonesMapper

### ISSUE THREAD

**Issue by JayMil** [googlei18n/libphonenumber#667]
Hello, 
I've been using the PhoneNumberToTimeZonesMapper to get time zones from phone numbers and I found a few in the United States that are not returning the correct time zone. 

Example Test
```java
//Test Wisconsin
String phone = "5342201462";
String country = "US";
PhoneNumberUtil phoneUtil = PhoneNumberUtil.getInstance();
PhoneNumberToTimeZonesMapper phoneTimeZoneMapper = PhoneNumberToTimeZonesMapper.getInstance();
 
List<String> timeZoneList = phoneTimeZoneMapper.getTimeZonesForNumber(phoneUtil.parse(phone, country));

assertTrue(timeZoneList.size() == 1);
assertEquals(timeZoneList.get(0), "America/Chicago"); //Fails, America/Los_Angels is found.
```

Results can be found at the repository
[PhoneNumberToTimeZoneTestResults](https://github.com/JayMil/PhoneNumberToTimeZoneTestResults)

Below is a description of the columns
**Phone Number:** The phone number tested. Phone numbers were derived from area code/prefix combos found at the following sites.  
* [allareacodes.com](http://www.allareacodes.com/)
  * Searching for an area code will bring up what prefix’s are valid.
* [nanpa.com](http://www.nanpa.com/area_code_maps/ac_map_static.html)
  * Clicking on the state code will display the area codes.

**Country Code:** The country code used with the phone number.
**Expected State:** The state the area code/prefix should belong to.
**Expected Time Zone:** The time zone that should be returned. If two time zones are present, it should be one of the two.
**Actual Returned Time Zone:** What was actually returned as the time zone.

These tests were done with the following jars
    libphonenumber:7.0.4
    geocoder:2.20
    carrier:1.9
    prefixmapper:2.20

Thanks

**Comment by dlyongemallo** [comment]
We've update the timezone mapping data. Can you check again?

**Comment by andyst** [comment]
libphonenumber 7.0.7 has been released. Can you please check again?

**Comment by JayMil** [comment]
I have checked again and I'm getting the same failing results when using the following jars
libphonenumber-7.0.7.jar
geocoder-2.23.jar
carrier-1.13.jar
prefixmapper-2.23.jar

I also updated to the newest javascript version and  now the following phone number is failing

phone number: 50328401
country code: BF

**Comment by jias0001** [comment]
By trying on the demo, the timezone for the US number 5342201462 is already working. If there are many more you think should be fixed, creating a pull requests would be the quickest way to get them fixed.

**Comment by JayMil** [comment]
Yes, sorry, the example above does work now, but my linked repository still has a list of 1,639 phone numbers that still do not work.  

[PhoneNumberToTimeZoneTestResults](https://github.com/JayMil/PhoneNumberToTimeZoneTestResults)

For example on googleLibPhoneIssues_1.csv 
Phone: 9382230000 (US)
Should be time zone [America/Chicago]
But is [America/Anguilla, America/Antigua, ...]

**Comment by jias0001** [comment]
Note that the way we derived the timezone mapping is by statistical analysis, so it won't be perfect. That being said, we will be very glad to accept a code patch from you. Please feel free to send us a pull request to address this if you want this to be fixed.

**Comment by keghani** [comment]
Closing this as a duplicate of the more up-to-date https://github.com/googlei18n/libphonenumber/issues/991.
