### ISSUE TITLE
Formatter for Brazilian recent 9th digit changes is not formatting properly

### ISSUE THREAD

**Issue by danielmaciel** [googlei18n/libphonenumber#854]
Hi!

The formatter for 31987654321 in Brazil should return this:
"31 98765-4321"

But it returns this instead:
"31987654321"

Still, the number is correctly recognized as valid.

**Comment by keghani** [comment]
Hi @danielmaciel!

Thanks for using our library :) Which format, and which release you using?
The latest release returns (31) 98765-4321 for the national format.

See http://libphonenumber.appspot.com/, entering "31987654321" and "BR" for steps 1 and 2 respectively.

I'll close the issue. Reasoning: working as intended
Please re-open if you reply with further questions.

Cheers,
keghani

**Comment by caioborges** [comment]
@danielmaciel it is fixed.

**Comment by danielmaciel** [comment]
Hi @keghani 

I know the Javascript demo website is working but the library is not.
I'm currently using 7.2.1 and PhoneNumberFormattingTextWatcher is still buggy.

Cheers,
Daniel

**Comment by keghani** [comment]
Hi @danielmaciel 

PhoneNumberFormattingTextWatcher is not in our library. How are you using this?

**Comment by danielmaciel** [comment]
@keghani  Oops, thanks a lot. Yeah It was our mistake.

**Comment by keghani** [comment]
Thanks for the quick response :) OK to close this issue?
