### ISSUE TITLE
Make Protobuf dependency optional

### ISSUE THREAD

**Issue by myanimal** [googlei18n/libphonenumber#913]
Since 7.2.0 `protobuf-java` is included as a dependency (as a jar in 7.2.1). On Android this can be an issue as it increases the dex method count for this library from 660 to **7106**.

The total dex method limit for an Android APK is ~65k, so this increase makes it very difficult to upgrade.

Using gradle I'm able to exclude the compile time protobuf dependency in 7.2.0, but since 7.2.1 it is included as a jar and I'm not sure how to exclude it.

    compile ('com.googlecode.libphonenumber:libphonenumber:7.2.0') {
        exclude module: 'protobuf-java'
    }

Is it possible to exclude this dependency when it is included as a jar?
If not, can it be changed back to a compile time dependency?

**Comment by dlyongemallo** [comment]
We're aware of this issue and are working to resolve it.

**Comment by myanimal** [comment]
@dlyongemallo any update on this?

**Comment by keghani** [comment]
@myanimal it is unlikely we can completely remove nanoproto dependencies from the Maven Central jar since nanoproto is a runtime dependency (see https://github.com/googlei18n/libphonenumber/issues/896 and https://github.com/googlei18n/libphonenumber/issues/906). It's still unclear how we can optimize the Android experience with this restriction. Do you have ideas? I'd be happy to look into a PR even if it's not completely fleshed out.

**Comment by myanimal** [comment]
@keghani hmm, I see.

Is it not possible to use [protobuf-javanano](http://mvnrepository.com/artifact/com.google.protobuf.nano/protobuf-javanano) as a compile-time maven dependency (maybe when it is out of alpha)? It could then be excluded when pulling in libphonenumber as described in my first post.

**Comment by keghani** [comment]
Thanks for finding that! That would actually be our best option. I had been looking at [protobuf-java](http://mvnrepository.com/artifact/com.google.protobuf/protobuf-java) (as of 3.0.0 it should contain nano, at least alpha and beta suggest this).

**Comment by myanimal** [comment]
Any progress on this? I haven't had time to even look at a PR.

**Comment by keghani** [comment]
Hi @myanimal,

3.0.0 is still in alpha. When it's more stable I'll look into prioritizing this.
We'll update the thread when there's progress - or you'll directly see results in release notes or jars.

**Comment by jpvirolainen** [comment]
Embedding the protobuf-java jar in libphonenumber is a very bad idea. It practically prevents the use of libphonenumber in any project using some other version of protobuf-java. In our case we're using grpc which is dependent on protobuf 3.0

**Comment by thefallentree** [comment]
Hi,

Please do not embed protobuf class directly in the jar. Besides the nano package,  you can either declare  a dependency on the maven package or repackage classes correctly (move them into com.google.i18n.libphonenumber.com.google.protobuf package for example.

As currently stands we can't solve conflicting issue unless copy code directly or modify jar ourselves. which are both very bad.

Thanks

**Comment by keghani** [comment]
Thanks for the hints @thefallentree!

We actually do not want to declare a dependency on the Maven releases of protobuf right now, this is not stable (see above).

Can you say more about the second option? What classes do you mean we should move to com.google.i18n.libphonenumber.com.google.protobuf?

**Comment by thefallentree** [comment]
everything under com.google.protobuf,   and you have to make sure all the code in that package use it 

checkout  https://maven.apache.org/plugins/maven-shade-plugin/

**Comment by moxie0** [comment]
I think @thefallentree is correct.  Bundling the protobuf code directly into your library is pretty weird, but if you have to do it, you should at least jarjar the protobuf package you're including directly to something that won't conflict with the actual dependency.  Right now anyone who has protobuf as a dependency of their own can't use your library.

I'm not clear on why it isn't possible for you to use a proper maven artifact here, but the workaround this library has chosen is extremely non-standard and pretty much breaks the java ecosystem.

**Comment by thefallentree** [comment]
any progress on this? This is blocking us using the latest library!

**Comment by keghani** [comment]
Thanks for sharing your concerns!

I agree that what we currently have is a hacky way to go about using javanano in the library, but unfortunately javanano isn't stable on Maven Central ([protobuf-javanano](http://mvnrepository.com/artifact/com.google.protobuf.nano/protobuf-javanano), [protobuf-java](http://mvnrepository.com/artifact/com.google.protobuf/protobuf-java)) or on [GitHub](https://github.com/google/protobuf/releases). At the time we switched to nano metadata this seemed to be our best option. We didn't think it would break backwards-compatibility, but we were wrong.

We're looking into fixing this cleanly so that all users and clients of the library can have a smoother experience without any more regressions. Please bear with us while we weigh our options. The last thing we want to do now is rush into a decision.

I understand you're frustrated, and we're actively working on a fix. Thanks for your patience.

**Comment by dleshem** [comment]
We're using libphonenumber on AppEngine, and your embedded protobuf code is incompatible with [gcloud-java](https://github.com/GoogleCloudPlatform/gcloud-java).

This causes the following runtime errors on our production AppEngine-
```java
java.lang.VerifyError: class com.google.datastore.v1beta3.LookupRequest$Builder overrides final method mergeUnknownFields.(Lcom/google/protobuf/UnknownFieldSet;)Lcom/google/protobuf/GeneratedMessage$Builder;
```

If you embed code from a 3rd-party library, you must change the namespace... e.g. change `com.google.protobuf` to `com.google.i18n.libphonenumber.repackaged.com.google.protobuf`.

**Comment by markstubhub** [comment]
Is it possible on Android to use the java plugin's compile exclude functionality, to eliminate the com.google.protobuf package from the jar. This doesn't seem to work: 

dependencies {
    compile project(':libraries-audio')
    compile project(':libraries-common')
    compile project(':libraries-core')
    compile('com.googlecode.libphonenumber:libphonenumber:7.3.1') {
        exclude module: 'protobuf-java'
    }
}

**Comment by grendell** [comment]
@markstubhub this will only work if the library is included as a dependency.  In this case, protobuf-java is included as a jar as of libphonenumber 7.2.1.

**Comment by mingtaozhangsc** [comment]
+1

**Comment by thefallentree** [comment]
What is taking this issue so long? This could be solved by an engineers in a hour 。Please get someone fix it .

**Comment by mingtaozhangsc** [comment]
@thefallentree are you doing that? If not, I've started.

**Comment by mingtaozhangsc** [comment]
I'm unable to push, the change needed is
```
            <configuration>
              <relocations>
                <relocation>
                  <pattern>com.google.protobuf</pattern>
                  <shadedPattern>libphonenumber.repackaged.com.google.protobuf</shadedPattern>
                </relocation>
              </relocations>
            </configuration>
```
from L49 after '</goals>' in https://github.com/googlei18n/libphonenumber/blob/master/java/libphonenumber/pom.xml

**Comment by keghani** [comment]
@mingtaozhangsc Thanks for the quick fix, I'd be happy to review a patch. To do this, please sign [the CLA](https://cla.developers.google.com/about/google-individual?csw=1) then submit a commit to your own fork, after which you can sent a PR.

**Comment by mingtaozhangsc** [comment]
@keghani Looks like my organization prevents me sign the CLA, @thefallentree @myanimal  are you able to do it?

**Comment by mingtaozhangsc** [comment]
@keghani Thank you for the efforts! What's the time line publishing to maven centrol? http://mvnrepository.com/artifact/com.googlecode.libphonenumber/libphonenumber

**Comment by keghani** [comment]
@mingtaozhangsc I pushed the shade plugin changes to 7.4.0: http://repo1.maven.org/maven2/com/googlecode/libphonenumber/libphonenumber/7.4.0/

I'm looking at other possibilities so I'll keep this issue open.

**Comment by mingtaozhangsc** [comment]
@keghani Sounds good, thank you!

**Comment by HTChang** [comment]
don't know why I still encounter this issue for  7.4.0
I tried 
    compile ('com.googlecode.libphonenumber:libphonenumber:7.4.0') {
        exclude module: 'protobuf-java'
    }
or without exclude
and still get

```
Execution failed for task ':app:transformResourcesWithMergeJavaResForInternalDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK META-INF/maven/com.google.protobuf/protobuf-java/pom.properties
  	File1: /Users/Howard_HT_Chang/.gradle/caches/modules-2/files-2.1/com.google.protobuf/protobuf-java/3.0.0-beta-2/de80fe047052445869b96f6def6baca7182c95af/protobuf-java-3.0.0-beta-2.jar
  	File2: /Users/Howard_HT_Chang/.gradle/caches/modules-2/files-2.1/com.googlecode.libphonenumber/libphonenumber/7.4.0/7f9b9b2db265c323f021ec1950a8901345288b9f/libphonenumber-7.4.0.jar
```

**Comment by keghani** [comment]
@HTChang I'm not sure - @mingtaozhangsc do you get the same issue?

**Comment by mingtaozhangsc** [comment]
@HTChang I'm not very familiar with gradle, is this 'app:transformResourcesWithMergeJavaResForInternalDebug' a standard gradle task? What does it do?

**Comment by adamsp** [comment]
@HTChang This occurs because the merge task tries to pull the same file (the pom files) from both the libphonenumber library and your other included protobuf library. Even though the class files have been shaded, looks like these artifacts stick around. You can exclude these:

```
android {
  packagingOptions {
    exclude 'META-INF/maven/com.google.protobuf/protobuf-java/pom.xml'
    exclude 'META-INF/maven/com.google.protobuf/protobuf-java/pom.properties'
  }
}
```

@mingtaozhangsc This task appears to be for merging non-code resources from different libraries - the "InternalDebug" part at the end appears to be a compile task specific to HTChang. There's a [similar issue here](http://stackoverflow.com/q/34031395/1217087).

This will all go away once the other dependency is stable - or possibly there's a way to exclude (or move?) the above files for this library - I'm not too familiar with maven, though.

**Comment by chadxz** [comment]
protobuf-java now has a 3.0.0 release available http://mvnrepository.com/artifact/com.google.protobuf/protobuf-java/3.0.0
https://github.com/google/protobuf/releases/tag/v3.0.0

I'm not sure whether this ticket was only being blocked on the stable release of 3.x or if there was something else too.

**Comment by keghani** [comment]
Thanks for the tip @chadxz! protobuf-java 3.0.0 actually doesn't have nano, but I did end up biting the bullet and depending on 3.0.0-alpha-7 protobuf-javanano, removing our own packaged dependencies (#1282). Release ETA end of this week, stay tuned!

**Comment by keghani** [comment]
Released in 7.6.0. See release notes: https://github.com/googlei18n/libphonenumber/releases/tag/libphonenumber-7.6.0
